spring:
  datasource:
    url: jdbc:mysql://119.28.8.143:3306/renshen?characterEncoding=utf-8&useSSL=false
    username: root
    password: yangjia*&^%$#@!2020
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/,file:/data/images/,file:E:/images/
