server:
  port: 80
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
  mvc:
    static-path-pattern: /**
  profiles:
    active: dev
