spring:
  datasource:
    url: jdbc:mysql://116.62.51.46:3306/renshen?characterEncoding=utf-8&useSSL=false
    username: root
    password: qavufcof
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/,file:/data/images/,file:E:/images/
