spring:
  datasource:
    url: jdbc:mysql://192.168.126.101:3306/renshen?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/,file:/data/images/
logging:
  level:
    com.renshen.mapper: debug
