spring:
  datasource:
    url: jdbc:mysql://119.28.8.143:13506/renshen?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: yangjia
    password: yangjia*&^%$#@2020
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/,file:/data/images/,file:E:/images/
